name: picture_learning
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
    sdk: '>=2.16.1 <3.0.0'

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.2

    # Functionalities
    http: ^0.13.4
    url_launcher: ^6.0.20
    audioplayers: ^0.20.1

    # State Managment
    flutter_bloc: ^8.0.1
    shared_preferences: ^2.0.13

    # Style
    expandable: ^5.0.1
    flutter_native_splash: ^2.1.3+1

    # Google Sign In
    google_sign_in: ^5.0.3

flutter_native_splash:
    color: '#11C0F9'
    image: assets/splash.png

    #color_dark: "#042a49"
    #background_image_dark: "assets/dark-background.png"
    #image_dark: assets/splash-invert.png
    #branding_dark: assets/dart_dark.png

    android_12:
        image: assets/splash12.png
        icon_background_color: '#ffffff'
        #image_dark: assets/android12splash-invert.png
        #icon_background_color_dark: "#eeeeee"

    android: true
    ios: true
    web: false

    #android_gravity: center
    #ios_content_mode: center
    #web_image_mode: center

    #fullscreen: true

    #info_plist_files:
    #  - 'ios/Runner/Info-Debug.plist'
    #  - 'ios/Runner/Info-Release.plist'

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^1.0.0

flutter:
    uses-material-design: true
    assets:
        - assets/img/
        - assets/icons/
