name: picture_learning
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
    sdk: '>=2.16.1 <3.0.0'

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.2
    http: ^0.13.4
    flutter_bloc: ^8.0.1
    google_sign_in: ^5.2.4
    shared_preferences: ^2.0.13

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^1.0.0

flutter:
    uses-material-design: true
    assets:
        - assets/img/
        - assets/icons/
